import { createDefaultModule, DefaultModuleContext, inject, LangiumServices, Module, PartialLangiumServices } from 'langium';
import { VsCoreGeneratedModule } from './generated/module';
import { VsCoreValidationRegistry, VsCoreValidator } from './vs-core-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type VsCoreAddedServices = {
    validation: {
        VsCoreValidator: VsCoreValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type VsCoreServices = LangiumServices & VsCoreAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const VsCoreModule: Module<VsCoreServices, PartialLangiumServices & VsCoreAddedServices> = {
    validation: {
        ValidationRegistry: (injector) => new VsCoreValidationRegistry(injector),
        VsCoreValidator: () => new VsCoreValidator()
    }
};

/**
 * Inject the full set of language services by merging three modules:
 *  - Langium default services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 */
export function createVsCoreServices(context?: DefaultModuleContext): VsCoreServices {
    return inject(
        createDefaultModule(context),
        VsCoreGeneratedModule,
        VsCoreModule
    );
}
